# Generated by Django 2.0.7 on 2018-07-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180708_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(db_index=True, related_name='_profile_friends_+', to='accounts.Profile'),
        ),
    ]
