# Generated by Django 2.0.7 on 2018-07-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='../static/facebook-avatar.jpg', null=True, upload_to='vidido/profile-phto', verbose_name='photo'),
        ),
    ]
